project:
  type: website
  execute-dir: file
  render:
    - "*.qmd"
    - "!readings/00-quarto/diamond-sizes.qmd"
    - "!readings/10-flexdashboard/*.Rmd"
    - "!readings/09-r-pkg-dev-1/*.qmd"
    - "!readings/01-command-line-1/*.qmd"
    
website:
  title: "Statistical Programming Paradigms and Workflows"
  navbar:
    search: true
    right:
      - icon: home
        text: "Home"
        file: index.qmd
      - icon: book-half
        text: "Course"
        href: lectures.qmd
      - icon: box-seam-fill
        text: "Resources"
        menu:
          - text: "Pre-reading"
            href: readings.qmd
          - text: "Projects"
            href: projects.qmd
      - icon: github
        href: https://github.com/jhustatprogramming2024
format:
  html:
    theme: simplex
    toc: true
    css: styles.css
    code-overflow: wrap

editor: source

execute:
  freeze: auto
